services:
  wechat-ocr-api:
    build: .
    container_name: wechat-ocr-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - USERNAME=admin
      - PASSWORD=password
